/* Firebird 3.0 */

-- ========================
-- 1. Таблица сообщений
-- ========================
CREATE TABLE messages (
    id          BIGINT     NOT NULL,
    chat_id     BIGINT     NOT NULL,
    user_id     BIGINT,
    username    VARCHAR(64),
    msg_date    TIMESTAMP,
    text        BLOB SUB_TYPE TEXT,
    raw_json    BLOB SUB_TYPE TEXT,
    tagged      SMALLINT   DEFAULT 0,
    ai_tagged   SMALLINT   DEFAULT 0,
    sentiment   VARCHAR(16),
    CONSTRAINT pk_messages PRIMARY KEY (id, chat_id)
);

-- ========================
-- 2. Теги (справочник)
-- ========================
CREATE TABLE tags (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) UNIQUE
);

-- ========================
-- 3. Связь Many-to-Many
-- ========================
CREATE TABLE message_tags (
    message_id  BIGINT     NOT NULL,
    chat_id     BIGINT     NOT NULL,
    tag_id      INTEGER    NOT NULL,
    processed   SMALLINT   DEFAULT 0,
    CONSTRAINT pk_message_tags PRIMARY KEY (message_id, chat_id, tag_id),
    CONSTRAINT fk_mt_msg FOREIGN KEY (message_id, chat_id)
        REFERENCES messages(id, chat_id) ON DELETE CASCADE,
    CONSTRAINT fk_mt_tag FOREIGN KEY (tag_id)
        REFERENCES tags(id) ON DELETE CASCADE
);

-- ========================
-- 4. Заметки (на будущее)
-- ========================
CREATE TABLE tag_actions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id    BIGINT,
    chat_id       BIGINT,
    tag_id        INTEGER,
    action        VARCHAR(32),
    action_by     VARCHAR(64),
    action_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================
-- 5. Индексы для скорости
-- ========================
CREATE INDEX idx_msg_chat_date  ON messages(chat_id, msg_date);
CREATE INDEX idx_tag_name       ON tags(name);
CREATE INDEX idx_mt_tag         ON message_tags(tag_id);
